-- Agregar columna user_email a centers para mostrar quién registró
ALTER TABLE public.centers ADD COLUMN IF NOT EXISTS user_email text;

-- Función para obtener email de un usuario (usada por moderadores)
CREATE OR REPLACE FUNCTION public.get_user_email(uid uuid)
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
AS $$
  SELECT email FROM auth.users WHERE id = uid;
$$;

-- Permitir eliminar centros a moderadores (UPDATE con status 'rejected' ya existe)
DROP POLICY IF EXISTS "Usuarios eliminan sus centros" ON public.centers;
CREATE POLICY "Usuarios eliminan sus centros"
  ON public.centers FOR DELETE
  USING (auth.uid() = user_id OR public.is_moderator());

-- Tabla de log de moderación
CREATE TABLE IF NOT EXISTS public.moderation_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  moderator_email text NOT NULL,
  center_id uuid REFERENCES public.centers(id) ON DELETE SET NULL,
  action text NOT NULL CHECK (action IN ('approved', 'rejected', 'edited', 'deleted', 'restored')),
  details text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.moderation_log ENABLE ROW LEVEL SECURITY;
GRANT SELECT, INSERT ON public.moderation_log TO authenticated;

CREATE POLICY "Moderators ven logs"
  ON public.moderation_log FOR SELECT
  USING (public.is_moderator());

CREATE POLICY "Moderators insertan logs"
  ON public.moderation_log FOR INSERT
  WITH CHECK (public.is_moderator());
