CREATE TABLE IF NOT EXISTS public.moderators (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL UNIQUE,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.moderators ENABLE ROW LEVEL SECURITY;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON public.moderators TO authenticated;

CREATE POLICY "Moderators son visibles pa todos"
  ON public.moderators FOR SELECT
  USING (true);

CREATE OR REPLACE FUNCTION public.is_moderator()
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT EXISTS (SELECT 1 FROM public.moderators WHERE email = auth.email());
$$;

DROP POLICY IF EXISTS "Usuarios editan sus centros" ON public.centers;
CREATE POLICY "Usuarios editan sus centros"
  ON public.centers FOR UPDATE
  USING (auth.uid() = user_id OR public.is_moderator())
  WITH CHECK (auth.uid() = user_id OR public.is_moderator());
